// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet.sql

package sqlc

import (
	"context"
)

const createFleet = `-- name: CreateFleet :one
INSERT INTO fleet (name, email)
VALUES ($1, $2)
RETURNING id, name, email
`

type CreateFleetParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateFleet(ctx context.Context, arg CreateFleetParams) (Fleet, error) {
	row := q.db.QueryRow(ctx, createFleet, arg.Name, arg.Email)
	var i Fleet
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const deleteFleet = `-- name: DeleteFleet :one
DELETE FROM fleet
WHERE id = $1
RETURNING id, name, email
`

func (q *Queries) DeleteFleet(ctx context.Context, id int64) (Fleet, error) {
	row := q.db.QueryRow(ctx, deleteFleet, id)
	var i Fleet
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getFleet = `-- name: GetFleet :one
SELECT id, name, email
FROM fleet
WHERE id = $1
`

func (q *Queries) GetFleet(ctx context.Context, id int64) (Fleet, error) {
	row := q.db.QueryRow(ctx, getFleet, id)
	var i Fleet
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const listFleets = `-- name: ListFleets :many
SELECT id, name, email
FROM fleet
ORDER BY id
`

func (q *Queries) ListFleets(ctx context.Context) ([]Fleet, error) {
	rows, err := q.db.Query(ctx, listFleets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fleet{}
	for rows.Next() {
		var i Fleet
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFleet = `-- name: UpdateFleet :one
UPDATE fleet
SET name = $2, email = $3
WHERE id = $1
RETURNING id, name, email
`

type UpdateFleetParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdateFleet(ctx context.Context, arg UpdateFleetParams) (Fleet, error) {
	row := q.db.QueryRow(ctx, updateFleet, arg.ID, arg.Name, arg.Email)
	var i Fleet
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
