// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Fleet struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Vehicle struct {
	ID      int64  `json:"id"`
	FleetID int64  `json:"fleet_id"`
	Model   string `json:"model"`
	Status  string `json:"status"`
}
