// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Priority string

const (
	PriorityLow  Priority = "low"
	PriorityMid  Priority = "mid"
	PriorityHigh Priority = "high"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type Fleet struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type SimpleRuleFleet struct {
	ID             int64          `json:"id"`
	FleetID        int64          `json:"fleet_id"`
	TargetField    string         `json:"target_field"`
	ThresholdValue pgtype.Numeric `json:"threshold_value"`
	Priority       Priority       `json:"priority"`
}

type SimpleRuleVehicle struct {
	ID             int64          `json:"id"`
	VehicleID      int64          `json:"vehicle_id"`
	TargetField    string         `json:"target_field"`
	ThresholdValue pgtype.Numeric `json:"threshold_value"`
	Priority       Priority       `json:"priority"`
}

type TelemetryHistory struct {
	ID               int64            `json:"id"`
	VehicleID        int64            `json:"vehicle_id"`
	Timestamp        pgtype.Timestamp `json:"timestamp"`
	SpeedMph         pgtype.Numeric   `json:"speed_mph"`
	FuelLevelPercent pgtype.Numeric   `json:"fuel_level_percent"`
	EngineState      string           `json:"engine_state"`
	OdometerMiles    pgtype.Numeric   `json:"odometer_miles"`
	Status           string           `json:"status"`
}

type Vehicle struct {
	ID      int64  `json:"id"`
	FleetID int64  `json:"fleet_id"`
	Model   string `json:"model"`
	Status  string `json:"status"`
}
