// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simple_rule_vehicle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSimpleRuleVehicle = `-- name: CreateSimpleRuleVehicle :one
INSERT INTO simple_rule_vehicle (vehicle_id, target_field, operator, threshold_value, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vehicle_id, target_field, operator, threshold_value, priority
`

type CreateSimpleRuleVehicleParams struct {
	VehicleID      int64          `json:"vehicle_id"`
	TargetField    string         `json:"target_field"`
	Operator       RuleOperator   `json:"operator"`
	ThresholdValue pgtype.Numeric `json:"threshold_value"`
	Priority       Priority       `json:"priority"`
}

func (q *Queries) CreateSimpleRuleVehicle(ctx context.Context, arg CreateSimpleRuleVehicleParams) (SimpleRuleVehicle, error) {
	row := q.db.QueryRow(ctx, createSimpleRuleVehicle,
		arg.VehicleID,
		arg.TargetField,
		arg.Operator,
		arg.ThresholdValue,
		arg.Priority,
	)
	var i SimpleRuleVehicle
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const deleteSimpleRuleVehicle = `-- name: DeleteSimpleRuleVehicle :one
DELETE FROM simple_rule_vehicle
WHERE id = $1
RETURNING id, vehicle_id, target_field, operator, threshold_value, priority
`

func (q *Queries) DeleteSimpleRuleVehicle(ctx context.Context, id int64) (SimpleRuleVehicle, error) {
	row := q.db.QueryRow(ctx, deleteSimpleRuleVehicle, id)
	var i SimpleRuleVehicle
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const getSimpleRuleVehicle = `-- name: GetSimpleRuleVehicle :one
SELECT id, vehicle_id, target_field, operator, threshold_value, priority
FROM simple_rule_vehicle
WHERE id = $1
`

func (q *Queries) GetSimpleRuleVehicle(ctx context.Context, id int64) (SimpleRuleVehicle, error) {
	row := q.db.QueryRow(ctx, getSimpleRuleVehicle, id)
	var i SimpleRuleVehicle
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const listSimpleRuleVehicleByVehicle = `-- name: ListSimpleRuleVehicleByVehicle :many
SELECT id, vehicle_id, target_field, operator, threshold_value, priority
FROM simple_rule_vehicle
WHERE vehicle_id = $1
`

func (q *Queries) ListSimpleRuleVehicleByVehicle(ctx context.Context, vehicleID int64) ([]SimpleRuleVehicle, error) {
	rows, err := q.db.Query(ctx, listSimpleRuleVehicleByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimpleRuleVehicle{}
	for rows.Next() {
		var i SimpleRuleVehicle
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.TargetField,
			&i.Operator,
			&i.ThresholdValue,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
