// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simple_rule_fleet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSimpleRuleFleet = `-- name: CreateSimpleRuleFleet :one
INSERT INTO simple_rule_fleet (fleet_id, target_field, operator, threshold_value, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, fleet_id, target_field, operator, threshold_value, priority
`

type CreateSimpleRuleFleetParams struct {
	FleetID        int64          `json:"fleet_id"`
	TargetField    string         `json:"target_field"`
	Operator       RuleOperator   `json:"operator"`
	ThresholdValue pgtype.Numeric `json:"threshold_value"`
	Priority       Priority       `json:"priority"`
}

func (q *Queries) CreateSimpleRuleFleet(ctx context.Context, arg CreateSimpleRuleFleetParams) (SimpleRuleFleet, error) {
	row := q.db.QueryRow(ctx, createSimpleRuleFleet,
		arg.FleetID,
		arg.TargetField,
		arg.Operator,
		arg.ThresholdValue,
		arg.Priority,
	)
	var i SimpleRuleFleet
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const deleteSimpleRuleFleet = `-- name: DeleteSimpleRuleFleet :one
DELETE FROM simple_rule_fleet
WHERE id = $1
RETURNING id, fleet_id, target_field, operator, threshold_value, priority
`

func (q *Queries) DeleteSimpleRuleFleet(ctx context.Context, id int64) (SimpleRuleFleet, error) {
	row := q.db.QueryRow(ctx, deleteSimpleRuleFleet, id)
	var i SimpleRuleFleet
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const getSimpleRuleFleet = `-- name: GetSimpleRuleFleet :one
SELECT id, fleet_id, target_field, operator, threshold_value, priority
FROM simple_rule_fleet
WHERE id = $1
`

func (q *Queries) GetSimpleRuleFleet(ctx context.Context, id int64) (SimpleRuleFleet, error) {
	row := q.db.QueryRow(ctx, getSimpleRuleFleet, id)
	var i SimpleRuleFleet
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.TargetField,
		&i.Operator,
		&i.ThresholdValue,
		&i.Priority,
	)
	return i, err
}

const listSimpleRuleFleetByFleet = `-- name: ListSimpleRuleFleetByFleet :many
SELECT id, fleet_id, target_field, operator, threshold_value, priority
FROM simple_rule_fleet
WHERE fleet_id = $1
`

func (q *Queries) ListSimpleRuleFleetByFleet(ctx context.Context, fleetID int64) ([]SimpleRuleFleet, error) {
	rows, err := q.db.Query(ctx, listSimpleRuleFleetByFleet, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimpleRuleFleet{}
	for rows.Next() {
		var i SimpleRuleFleet
		if err := rows.Scan(
			&i.ID,
			&i.FleetID,
			&i.TargetField,
			&i.Operator,
			&i.ThresholdValue,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
