// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTelemetryHistory = `-- name: CreateTelemetryHistory :one
INSERT INTO telemetry_history (vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status
`

type CreateTelemetryHistoryParams struct {
	VehicleID        int64            `json:"vehicle_id"`
	Timestamp        pgtype.Timestamp `json:"timestamp"`
	SpeedMph         pgtype.Numeric   `json:"speed_mph"`
	FuelLevelPercent pgtype.Numeric   `json:"fuel_level_percent"`
	EngineState      string           `json:"engine_state"`
	OdometerMiles    pgtype.Numeric   `json:"odometer_miles"`
	Status           string           `json:"status"`
}

func (q *Queries) CreateTelemetryHistory(ctx context.Context, arg CreateTelemetryHistoryParams) (TelemetryHistory, error) {
	row := q.db.QueryRow(ctx, createTelemetryHistory,
		arg.VehicleID,
		arg.Timestamp,
		arg.SpeedMph,
		arg.FuelLevelPercent,
		arg.EngineState,
		arg.OdometerMiles,
		arg.Status,
	)
	var i TelemetryHistory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Timestamp,
		&i.SpeedMph,
		&i.FuelLevelPercent,
		&i.EngineState,
		&i.OdometerMiles,
		&i.Status,
	)
	return i, err
}

const getTelemetryHistory = `-- name: GetTelemetryHistory :one
SELECT id, vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status
FROM telemetry_history
WHERE id = $1
`

func (q *Queries) GetTelemetryHistory(ctx context.Context, id int64) (TelemetryHistory, error) {
	row := q.db.QueryRow(ctx, getTelemetryHistory, id)
	var i TelemetryHistory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Timestamp,
		&i.SpeedMph,
		&i.FuelLevelPercent,
		&i.EngineState,
		&i.OdometerMiles,
		&i.Status,
	)
	return i, err
}

const listLatestTelemetryByVehicle = `-- name: ListLatestTelemetryByVehicle :many
SELECT id, vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status
FROM telemetry_history
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type ListLatestTelemetryByVehicleParams struct {
	VehicleID int64 `json:"vehicle_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) ListLatestTelemetryByVehicle(ctx context.Context, arg ListLatestTelemetryByVehicleParams) ([]TelemetryHistory, error) {
	rows, err := q.db.Query(ctx, listLatestTelemetryByVehicle, arg.VehicleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryHistory{}
	for rows.Next() {
		var i TelemetryHistory
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Timestamp,
			&i.SpeedMph,
			&i.FuelLevelPercent,
			&i.EngineState,
			&i.OdometerMiles,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryHistoryByVehicle = `-- name: ListTelemetryHistoryByVehicle :many
SELECT id, vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status
FROM telemetry_history
WHERE vehicle_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListTelemetryHistoryByVehicle(ctx context.Context, vehicleID int64) ([]TelemetryHistory, error) {
	rows, err := q.db.Query(ctx, listTelemetryHistoryByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryHistory{}
	for rows.Next() {
		var i TelemetryHistory
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Timestamp,
			&i.SpeedMph,
			&i.FuelLevelPercent,
			&i.EngineState,
			&i.OdometerMiles,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTelemetryHistoryStatus = `-- name: UpdateTelemetryHistoryStatus :one
UPDATE telemetry_history
SET status = $2
WHERE id = $1
RETURNING id, vehicle_id, timestamp, speed_mph, fuel_level_percent, engine_state, odometer_miles, status
`

type UpdateTelemetryHistoryStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTelemetryHistoryStatus(ctx context.Context, arg UpdateTelemetryHistoryStatusParams) (TelemetryHistory, error) {
	row := q.db.QueryRow(ctx, updateTelemetryHistoryStatus, arg.ID, arg.Status)
	var i TelemetryHistory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Timestamp,
		&i.SpeedMph,
		&i.FuelLevelPercent,
		&i.EngineState,
		&i.OdometerMiles,
		&i.Status,
	)
	return i, err
}
