// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package sqlc

import (
	"context"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicle (fleet_id, model, status)
VALUES ($1, $2, $3)
RETURNING id, fleet_id, model, status
`

type CreateVehicleParams struct {
	FleetID int64  `json:"fleet_id"`
	Model   string `json:"model"`
	Status  string `json:"status"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle, arg.FleetID, arg.Model, arg.Status)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.Model,
		&i.Status,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :one
DELETE FROM vehicle
WHERE id = $1
RETURNING id, fleet_id, model, status
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRow(ctx, deleteVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.Model,
		&i.Status,
	)
	return i, err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, fleet_id, model, status
FROM vehicle
WHERE id = $1
`

func (q *Queries) GetVehicle(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.Model,
		&i.Status,
	)
	return i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, fleet_id, model, status
FROM vehicle
ORDER BY id
`

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.FleetID,
			&i.Model,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByFleet = `-- name: ListVehiclesByFleet :many
SELECT id, fleet_id, model, status
FROM vehicle
WHERE fleet_id = $1
ORDER BY id
`

func (q *Queries) ListVehiclesByFleet(ctx context.Context, fleetID int64) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByFleet, fleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.FleetID,
			&i.Model,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicle
SET fleet_id = $2, model = $3, status = $4
WHERE id = $1
RETURNING id, fleet_id, model, status
`

type UpdateVehicleParams struct {
	ID      int64  `json:"id"`
	FleetID int64  `json:"fleet_id"`
	Model   string `json:"model"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.FleetID,
		arg.Model,
		arg.Status,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.FleetID,
		&i.Model,
		&i.Status,
	)
	return i, err
}
